info:
  profile: default
#server
server:
  port: 8080
  contextPath: /secServer

spring:
  #http
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  #mvc
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH\:mm\:ss
  #druid
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/jeesns?useUnicode=true&characterEncoding=UTF-8
      username: jeesns_admin
      password: jeesns_admin
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 8
      max-wait: 60000
      pool-prepared-statements: true 
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 20000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 1800000
      max-evictable-idle-time-millis: 3600000
      filters: stat,wall,log4j  
  #thymeleaf
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  #aop
  aop:
    proxy-target-class: true
  # REDIS (RedisProperties)
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: localhost  # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456  # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 8    # 连接池中的最大空闲连接
      min-idle: 0    # 连接池中的最小空闲连接
    timeout: 0    # 连接超时时间（毫秒）
    shared:
      database: 3  # Redis数据库索引（默认为0）
      host: localhost  # Redis服务器地址
      port: 6379 # Redis服务器连接端口
      password: 123456  # Redis服务器连接密码（默认为空）
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8    # 连接池中的最大空闲连接
        min-idle: 0    # 连接池中的最小空闲连接
      timeout: 0    # 连接超时时间（毫秒）
  #rabbimq
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

#mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
    - classpath*:com/lhy/si/**/mapper/*.xml
#tkmapper
mapper:
    mappers:
        - tk.mybatis.mapper.common.Mapper
    not-empty: false
    identity: MYSQL
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#swagger
swagger:
  enabled: true
  title: siApp-secServer
  description: 社交app用户中心
  version: 1.0.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: http://blog.csdn.net/v2sking
  contact.name: 再见尼罗河
  contact.url: http://blog.csdn.net/v2sking
  contact.email: 1591963820@163.com
  base-package: com.si
  base-path: /**
  exclude-path: /error, /ops/**
  globalOperationParameters:
    - name: token 
      description: jwt令牌
      modelRef: string
      parameterType: header
      required: false
  docket:
    user: 
      title: 用户
      description: 用户相关
      base-path: /user/**
    role: 
      title: 角色
      description: 查询角色接口
      base-path: /role/**
    api:
      title: api接口
      description: 查询角色api权限接口
      base-path: /api/**
      
si:
  mq:
    type: rabbit
  sec:
    anon:
      paths:
        - /role/getByUserId
        - /api/getByRoleId
        - /user/get
        - /user/register
        - /user/login
        - /login/**
        - /login*
        - /index/**
        - /index*

flyway:
  baselineOnMigrate: true
